version: "3.3"
services:
  db:
    image: 'postgres:13.4-alpine'
    container_name: 'postgresnew'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ft_transcendence
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  frontend:
    build: ./srcs/frontend
    ports:
      - 8080:8080
    volumes: 
      - ./srcs/frontend:/app
      - /app/node_modules/
  backend: 
    build: ./backend
    ports: 
      - 3000:3000
      - 81:81
      - 82:82
      - 83:83
      - 84:84
    volumes:
      - ./srcs/backend:/app
      - /app/node_modules/
    env_file:
      - ./srcs/backend/.env
volumes: 
  pgdata: